### ISSUE TITLE
Broken link from GitHub to Jenkins CI BlueOcean view

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1054]
The link from GitHub to BlueOcean is still broken. It may be fixed by adjusting the apache configuration, see http://buildserver.deegree.org/view/All/job/deegree-3.4/job/pull-request/

**Comment by stephanr** [comment]
From the generated URLs it is not really convenient to have an encoded slash, because such parts tend to cause problems.
A possible approach could therefore be to examine whether this slash can be omitted or replaced by configuration.

**Comment by tfr42** [comment]
Apache Tomcat is configured as described in: https://plugins.jenkins.io/blueocean-config/ 

Apache httpd is configured as described in:
https://wiki.jenkins.io/display/JENKINS/Running+Jenkins+behind+Apache

**Comment by stephanr** [comment]
The defined changes were not activated because they have not been applied when the jenkins was started. This was triggered by the fact that tomcat is now a systemctl service.

I have renamed tomcat_hudson to tomcat_hudson.ign in /usr/local/tomcat/hudson/bin to reflect that and refactored the settings for tomcat.

Java environment JAVA_OPTS/CATALINA_OPTS are now set in `/usr/local/tomcat/hudson/bin/setenv.sh` instead of the systemctl service declaration at `/etc/systemd/system/tomcat_hudson.service`.

The settings for HTTP and HTTPs have also been aligned with regard to the above-mentioned documentation.

It looks to me as if the configuration now works as intended. 

@tfr42 Could you please review the merged Jenkins parameters?

**Comment by tfr42** [comment]
Services are still up and running. The parameters seems to be fine. The redirect from GitHub works now.
