### ISSUE TITLE
IsSurface with XPathExpression fails

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1100]
Example:
```
 <ogc:Function name="IsSurface">
    <ogc:PropertyName>bu-core2d:geometry2D/bu-base:BuildingGeometry2D/bu-base:geometry</ogc:PropertyName>
</ogc:Function>
```
GetMap does not render the features. Warning in the log: `[07:36:09] WARN: [SymbologyParser?] Evaluating the following expression resulted in an error 'The IsSurface? function's first argument did not evaluate to a geometry.'`

**Comment by stempler** [comment]
Looks like this fails because https://github.com/deegree/deegree3/blob/1e609576f89457df84ea66c2b688bdf3a40d9137/deegree-core/deegree-core-base/src/main/java/org/deegree/filter/utils/FilterUtils.java#L55 is called with a `GenericXMLElement` as parameter that has the geometry in its `children` collection.
