### ISSUE TITLE
Example templates in the deegree console invalid 

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#1491]
The xml is valid, but the validation in the deegree console shows some failures.

**Layers:**

* The example template of a FeatureLayer is invalid:
`Error near line 15, column 13: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.deegree.org/layers/base":Name}'. One of '{"http://www.deegree.org/layers/feature":SortBy}' is expected.`
* GdalLayerStore does not have a schemaLocation specified and is invalid:
`Error near line 4, column 13: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.deegree.org/layers/base":Name}'. One of '{"http://www.deegree.org/layers/gdal":File}' is expected.`

**Themes**
* The type 'Standard' is invalid:
`Error near line 11, column 14: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.deegree.org/metadata/description":Title}'. One of '{"http://www.deegree.org/themes/standard":Layer, "http://www.deegree.org/themes/standard":Theme}' is expected.
        Error near line 17, column 16: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.deegree.org/metadata/description":Title}'. One of '{"http://www.deegree.org/themes/standard":Layer, "http://www.deegree.org/themes/standard":Theme}' is expected.`

**Comment by stephanr** [comment]
I started the RC1 in docker with changed logging and got this error:
```
2023-06-22 11:40:51,941 TRACE [org.deegree.console.generic.XmlEditorBean] <> null
```
Which relates to the following line:
https://github.com/deegree/deegree3/blob/9e4376f38fd56e94091b18be5de16c270fe245d0/deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/XmlEditorBean.java#L129
After setting a Breakpoint this was only called once and created an NPE because `resourceProviderClass` was `null`.
I could not determine if this relates to the usability of the console or not.

After checking the validation function in:
https://github.com/deegree/deegree3/blob/9e4376f38fd56e94091b18be5de16c270fe245d0/deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/XmlEditorBean.java#L315

It looks like the schemas are referenced with full path inside jar `jar:file:/usr/local/tomcat/webapps/deegree-webservices/WEB-INF/lib/deegree-layers-feature-3.5-RC1.jar!/META-INF/schemas/layers/feature/feature.xsd` which will create an issue with relative resolution.

**Comment by stephanr** [comment]
While debugging the issue i tested manually setting the schema location to `/META-INF/schemas/layers/feature/feature.xsd` which worked.
Following this route i created the PR #1535.
