### ISSUE TITLE
SEF URLs

### ISSUE THREAD

**Issue by kraaka** [deegree/deegree3#502]
Apache config needs some adjustments for usage of SEF URLs:

https://docs.joomla.org/Enabling_Search_Engine_Friendly_%28SEF%29_URLs

**Comment by stephanr** [comment]
There was only a small change in the VirtualHost definition of the apache2 settings needed, so i enabled this and copied the default htaccess.txt template from joomla, so from the server side everything is prepared.

(For example http://www.deegree.org/Download already works)

So please chanhge the administrator setting in joomla, so that jommla creates the links without the index.php.

**Comment by kraaka** [comment]
done
