### ISSUE TITLE
FeatureStore GML application schema wizard does not map some feature types

### ISSUE THREAD

**Issue by matteomatassoni** [deegree/deegree3#552]
Using Deegree 3.3.14, I have tried creating a SQL feature store with the
"Create tables from GML application schema" option, and Relational storage mode. The application schema used is [Species Distribution](http://inspire.ec.europa.eu/schemas/sd/3.0/SpeciesDistribution.xsd) from [INSPIRE] (http://inspire.ec.europa.eu).

Everthing goes fine until I import a custom GML dataset getting this output from deegree:

> "GML import failed: Error inserting feature: Cannot insert feature of type '{http://inspire.ec.europa.eu/schemas/sd/3.0}SpeciesDistributionUnit'. No mapping defined and BLOB mode is off.". 

Checking the generated SQL Feature store xml file I can see that deegree only generates the feature type mapping for `SpeciesDistributionDataSet` and not also for `SpeciesDistributionUnit`.

*Please note* that my GML dataset that is valide against Species Distribution schema

**Comment by MrSnyder** [comment]
The problem is that the mapping wizard is not fully supported yet. It's in beta stage [1] and does not handle every corner case of any GML application schema. To be clear about this: Sometimes it simply leaves out stuff.

However, you should be able to manually create a mapping configuration for SpeciesDistributionUnit. Some helpful tips can be found at [2].

[1] http://download.deegree.org/documentation/3.3.14/html/featurestores.html#auto-generating-a-mapping-configuration-and-tables
[2] http://download.deegree.org/documentation/3.3.14/html/featurestores.html#recommended-workflow

**Comment by matteomatassoni** [comment]
I think I have found the problem. First of all the problem is not a bug in the wizard, but it is how deegree reads this GML app schema. In particular, deegree treats `SpeciesDistributionUnit`as a `GenericFeatureCollectionType` and due to this it skipped in the process of generating the mappings. Even if I choose to manually create a mapping configuration, the feature store continues to treat `SpeciesDistributionUnit` as a feature collection, and as a consequence I can not import my dataset.

I think the problem can be related to the method `isGML32FeatureCollection`of `GMLSchemaInfoSet`class.

**Comment by tfr42** [comment]
@matteomatassoni Thanks for posting the work-around. For now I will close the ticket. In case you have further comments please re-open or send a question to the [deegree-users mailing list] (http://www.deegree.org/community).
