### ISSUE TITLE
WMTS integration tests are failing

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#564]
Currently the wmts integration tests are failing. These tests depend on the 'utah-workspace' running at 'deegree3-demo.deegree.org'. The service is up and running but it returns blank images for the layer 'dominantvegetation'. Could someone have a look at it?

Test url: http://deegree3-demo.deegree.org/utah-workspace/services?LAYERS=dominantvegetation&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A900913&BBOX=-13958375.99444,4430686.1547411,-10905786.83339,5441489.4166033&WIDTH=2496&HEIGHT=826

**Comment by tfr42** [comment]
This issue is blocking the release of deegree since this test is used in integration test suite. 
The configuration in https://github.com/deegree/deegree3/blob/master/deegree-tests/deegree-wmts-tests/src/main/webapp/WEB-INF/workspace/datasources/remoteows/utah.xml points to http://deegree3-demo.deegree.org/utah-workspace/services?request=GetCapabilities&amp;service=WMS&amp;version=1.1.1 which works and returns valid data (see link above - shows a colorful image).

**Comment by tfr42** [comment]
Issue is not reproducible anymore. I consider this as solved.
@copierrj please re-run the release job.

**Comment by dstenger** [comment]
The Travis-CI Jobs are still failing due to the WMTS integration tests. We have made some investigations to find out the reason and concluded that the utah workspace on 'deegree3-demo.deegree.org' seems to be broken. This could be tested by setting up the deegree-workspace-utah with the latest deegree-webservice and configuring this in the integrated deegree-wmts-test workspace as remote WMS. 
E.g. the test 'remotewms1'
```
  WmtsSimilarityIT.testSimilarity:106 Images are not similar enough for remotewms1.kvp, request: http://localhost:1025/deegree-wmts-tests/services?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=remotewms&STYLE=default&TILEMATRIXSET=utah&TILEMATRIX=7142.857142857143&TILEROW=0&TILECOL=0&FORMAT=image%2Fpng
[13:27:09] DEBUG: [OGCFrontController] Dispatching request to OWS class: org.deegree.services.wmts.controller.WMTSController
```
executes the request: http://deegree3-demo.deegree.org/utah-workspace/services?height=256&bbox=441174.0%2C4455527.0%2C441686.0%2C4456039.0&width=256&layers=orthophoto%2Cdominantvegetation&request=GetMap&service=WMS&styles=default%2Cdefault&srs=EPSG%3A26912&format=image%2Fpng&transparent=true&version=1.1.1

The returning image does not match the expected one [1].

We propose the further steps:
 1. Update of deegree3-demo.deegree.org (consider that also the deployed webapp could contain errors; this should be checked as well).
 2. Rerun Travis-CI
 3. Further investigations if test is still failing

[1] https://github.com/lat-lon/deegree3/blob/master/deegree-tests/deegree-wmts-tests/src/test/requests/remotewms1.response

**Comment by dstenger** [comment]
We updated the utah demo (http://deegree3-demo.deegree.org/utah-workspace/) from version 3.3.14 to 3.3.15 (this includes the webapp and workspace) and cleaned the work and temp directory of the tomcat.

Now, the WMTS integration tests pass again. We tested this by building a current pull request: https://github.com/deegree/deegree3/pull/602

**Comment by tfr42** [comment]
All integration test work again. We can close this issue since we have been able to build the 3.4-pre18 release.
