### ISSUE TITLE
loss of performance in 3.4-pre18 SQLFeatureStore

### ISSUE THREAD

**Issue by lgoltz** [deegree/deegree3#612]
Commit https://github.com/deegree/deegree3/commit/b25892700f21a47b388265284b8a8370a3335e53 leads to a loss of performance in deegree-3.4-pre18. The commit was part of the pull requests #526  and #527. 
The same WFS GetFeature request can be answered with 3.4-pre17 in ~0,3 seconds, in 3.4-pre18 it needs ~27,7 seconds (the same workspace is used). 
The method causing the problem is #recreatePropertyFromGml() in org.deegree.feature.persistence.sql.rules.FeatureBuilderRelational.

**Comment by MrSnyder** [comment]
That's bad.

The goal of the mentioned commits is to ensure that mapped GML objects are represented using the correct classes of deegree's TypeObjectNode hierarchy. My use case is the correct in-memory filtering of gml:TimeInstant and gml:TimePeriod elements for an SQLFeatureStore configuration for AIXM documents. For that, such elements need to be represented as TimeInstant-/TimePeriod-objects.

I am aware that the taken approach is somewhat hacky, but I didn't realize that it would affect any relevant use cases. Can you identify the relevant mappings in your SQLFeatureStore configuration?

The idea of the patch is to simply use deegree's GML parser for any in order to transform GenericXmlElement instances into TimeInstant-/TimePeriod-objects. This way, I was able to avoid the huge code changes that "native" relational building of such objects would introduce ( for now).

A possible quick fix could be to put a check  after line 328 in FeatureBuilderRelational. Here, we could try to determine if this is a property that contains a gml:TimeInstant or a gml:TimePeriod object. Otherwise, we should skip the call to recreatePropertyFromGml. However, it should first be clarified for which kind of element mapping the regression occurs.

**Comment by lgoltz** [comment]
Here is the FeatureTypeMapping of the requested FeatureType:
```xml
<FeatureTypeMapping name="dog:Hauskoordinaten" table="haus">
        <FIDMapping prefix="BB_HK_">
            <Column name="gid" type="integer"/>
        </FIDMapping>
        <Primitive path="iso19112:geographicIdentifier" mapping="geographicidentifier"/>
        <Complex path="iso19112:geographicExtent">
            <Complex path="gmd:EX_BoundingPolygon">
                <Complex path="gmd:polygon">
                    <Geometry path="." mapping="geographicextent">
                        <StorageCRS srid="25833">urn:ogc:def:crs:EPSG::25833</StorageCRS>
                    </Geometry>
                </Complex>
            </Complex>
        </Complex>
        <Geometry path="iso19112:position" mapping="position">
            <StorageCRS srid="25833">urn:ogc:def:crs:EPSG::25833</StorageCRS>
        </Geometry>
        <Complex path="iso19112:gazetteer">
            <Join fromColumns="locationtype" toColumns="id" table="si_locationtype"/>
            <Feature path=".">
                <Join fromColumns="gaz_id" toColumns="gazetteer_id" table="si_gazetteer"/>
            </Feature>
        </Complex>
        <Complex path="iso19112:locationType">
            <Feature path=".">
                <Join fromColumns="locationtype" toColumns="id" table="si_locationtype"/>
            </Feature>
        </Complex>
        <Primitive path="iso19112:parent" mapping="parent"/>
        <Primitive path="dog:qualitaet" mapping="qualitaet"/>
        <Primitive path="dog:datensatznummer" mapping="datensatznummer"/>
        <Primitive path="dog:land" mapping="land"/>
        <Primitive path="dog:regierungsbezirk" mapping="regierungsbezirk"/>
        <Primitive path="dog:kreis" mapping="kreis"/>
        <Primitive path="dog:gemeinde" mapping="gemeinde"/>
        <Primitive path="dog:ortsteil" mapping="ortsteil"/>
        <Primitive path="dog:strasse" mapping="strasse"/>
		<!-- <Primitive path="dog:hausnummer" mapping="hausnr"/>
		Sollen als INT in LGb ausgegeben werden, anderes mapping -->
        <Primitive path="dog:hausnummer" mapping="hausnummer_int"/>
        <Primitive path="dog:hausnummernzusatz" mapping="hausnummernzusatz"/>
        <Primitive path="dog:hausschluessel" mapping="hausschluessel"/>
        <Primitive path="dog:strassenname" mapping="strassenname"/>
        <Primitive path="dog:strassenname_normalisiert" mapping="strassenname_normalisiert"/>
        <Primitive path="dog:strassenname_soundex" mapping="strassenname_soundex"/>
        <Primitive path="dog:ortsteilname" mapping="ortsteilname"/>
        <Primitive path="dog:ortsteilname_normalisiert" mapping="ortsteilname_normalisiert"/>
        <Primitive path="dog:postleitzahl" mapping="postleitzahl"/>
        <Primitive path="dog:postOrtsteil" mapping="postortsteil"/>
        <Primitive path="dog:postOrtsteil_normalisiert" mapping="postortsteil_normalisiert"/>
        <Primitive path="dog:ortsnamePost" mapping="ortsnamePost"/>
        <Primitive path="dog:ortsnamePost_normalisiert" mapping="ortsnamePost_normalisiert"/>
        <Primitive path="dog:zusatzOrtsname" mapping="zusatzortsname"/>
        <Primitive path="dog:zusatzOrtsname_normalisiert" mapping="zusatzortsname_normalisiert"/>
    </FeatureTypeMapping>
```
As fas as I see recreatePropertyFromGml is called for each complex mapping.

**Comment by tfr42** [comment]
@vog Since this fix effects the enhancement added with #527 please have a look.

**Comment by vog** [comment]
@MrSnyder Do you think your proposed solution (add check in FeatureBuilderRelational) is applicable for that FeatureTypeMapping provided by @lgoltz or do we need a different solution?

**Comment by MrSnyder** [comment]
Yes, it should be applicable. @lgoltz: Is it possible to check the proposed fix for your use case?

**Comment by lgoltz** [comment]
With the (already merged fix) our customer achieves the  same request time as before. So, I will close this issue.
