### ISSUE TITLE
deegree.org (without subdomain) doesn't work

### ISSUE THREAD

**Issue by copierrj** [deegree/deegree3#636]
Not only http://www.deegree.org but also http://deegree.org should work.

**Comment by stephanr** [comment]
Checking the dns entries via nslookup gave the follwing results:
```
$ nslookup deegree.org
...
*** Can't find deegree.org: No answer

$ nslookup www.deegree.org
...
www.deegree.org canonical name = plaza.deegree.org.
...
```
As a result i would suggest to also add a CNAME for deegree.org.

**Comment by tfr42** [comment]
Provide @stephanr with the last name server configuration for the server plaza.deegree.org

**Comment by stephanr** [comment]
For the DNS-Related Issue i would like to suggest to apply following configuration:
```
@                        IN A       136.243.175.5
plaza                    IN A       136.243.175.5
*                        IN CNAME   plaza
``` 
If there are other aliases for plaza ( ... IN CNAME plaza) these should be removed.

This configuration fragment is in bind Syntax and declares:
- deegree.org is mapped to 136.243.175.5 (plaza.deegree.org) (Here is a A record required, since @ with CNAME ist a combination that should be avoided)
- plaza.deegree.org is mapped to 136.243.175.5
- all other not in the nameserver configured names are mapped to plaza as an alias

The result would be, that the tmc can hanlde all used subdomains *.deegree.org at the server plaza.deegree.org.

Currently there are the following names that are assigned in the webserver of plaza:
 - apidoc.deegree.org
 - buildserver.deegree.org
 - demo.deegree.org, with alias: deegree3-demo.deegree.org deegree3-testing.deegree.org
 - download.deegree.org
 - ogcri.deegree.org, with alias: cite.deegree.org
 - repo.deegree.org, with alias: nexus.deegree.org
 - schemas.deegree.org
 - wiki.deegree.org
 - www.deegree.org, with alias deegree.org www.deegree.net deegree.net www.deegree.de deegree.de

**Comment by tfr42** [comment]
Currently mapped URLs:
    ​http://apidoc.deegree.org: directory listing
    ​http://artefacts.deegree.org: Apache default page
    ​http://buildserver.deegree.org: jenkins CI
    ​http://cite.deegree.org: empty page
    ​http://deegree3-demo.deegree.org: ​http://www.deegree.org/Demo
    ​http://deegree3-testing.deegree.org: ​http://www.deegree.org/Demo
    ​http://demo.deegree.org: ​http://www.deegree.org/Demo (Demo page)
    ​http://download.deegree.org: ​http://www.deegree.org/Download (Download page)
    ​http://drupal.deegree.org: Apache default page
    ​http://drupal-test.deegree.org: Apache default page
    ​http://nexus.deegree.org: Nexus Repository Manager
    ​http://ogcri.deegree.org: empty page
    ​http://plaza.deegree.org: Apache default page
    ​http://repo.deegree.org: Nexus Repository Manager 
    ​http://schemas.deegree.org: directory listing
    ​http://wiki.deegree.org: wiki start page

**Comment by tfr42** [comment]
Request ticket for OSGeo Sysadmins: https://trac.osgeo.org/osgeo/ticket/2006

**Comment by tfr42** [comment]
Now deegree.org is reachable, tested with FF and Chrome.
We need to answer on https://trac.osgeo.org/osgeo/ticket/2006#comment:4

**Comment by copierrj** [comment]
@tfr42 Replacing current list of subdomains with a wildcard is fine with the TMC.

**Comment by stephanr** [comment]
As discussed in the TMC meeting today, i will enhance the Webserver configuration that every unknown subdomain will be redirected to the website (www.deegree.org).

**Comment by stephanr** [comment]
The Webserver configuration has been updated any unknown subdomains will now be redirected to www.deegree.org (this change had been made in the default site configuration).

**Comment by tfr42** [comment]
https://trac.osgeo.org/osgeo/ticket/2006#comment:6

Waiting for answer from Martin.

**Comment by tfr42** [comment]
Resolved, see https://trac.osgeo.org/osgeo/ticket/2006#comment:9
