### ISSUE TITLE
Enable handling of wfs parameters startindex and count in datastores

### ISSUE THREAD

**Issue by copierrj** [deegree/deegree3#648]
For database backed datastores it would be nice to implement handling of startindex and count by adding the appropriate stuff into the sql query.

**Comment by tfr42** [comment]
A solution shall support:
- SQLFeatureStore with relational mapping
- SQLFeatureStore with blob-mapping

for the SQL dialects:
- PostGISDialect
- OracleDialect
- MSSQLDialect

Integration test shall verify the expected behavior against the DBMS versions listed in the compatibility matrix https://github.com/deegree/deegree3/wiki/End-of-Life-and-Support-Matrix

**Comment by tfr42** [comment]
Related to https://github.com/deegree/deegree3/pull/832
