### ISSUE TITLE
Test the extended feature for WFS-T INSERT action to resolve features from FeatureStore

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#864]
After the PR #820 is merged this needs additional testing.
 - [x] one test with the feature disabled and two WFS-T INSERT actions with expected result of an error message and no data inserted
 - [x] additional test with feature enabled and two WFS-T INSERT without error and all features inserted

**Comment by marcus-mohr** [comment]
I'll test

**Comment by copierrj** [comment]
@marcus-mohr: thanks

**Comment by marcus-mohr** [comment]
I've tested the feature and tried to insert transformed data of the inspire theme _addresses_. The data consists of two feature types: _house coordinates_ (orig: hauskoordinaten) and _keys_ (orig: schlüssel). You can find data and workspace here: [deegreeRC5-test-#864.zip](https://github.com/deegree/deegree3/files/1478578/deegreeRC5-test-.864.zip)

Unfortunately I wasn't able to insert features which have a reference to already inserted features . I've taken these steps:
1. Inserting the _keys_ with `allowFeatureReferencesToDatastore="false"`
Result: First insert -> no Problem

2. Inserting the _house coordinates_ with `allowFeatureReferencesToDatastore="false"`
Result: As expected the following error appears: 
_Request failed: Cannot perform insert operation: Unable to resolve reference to '#AdminUnitName_12'._

3. Inserting the _house coordinates_ with `allowFeatureReferencesToDatastore="true"`
Result: Unexpected error appears:
_Request failed: Cannot perform insert operation: Unable to determine feature type for id 'AdminUnitName_12'. Given id does not start with a configured identifier prefix. Known prefixes are: 'TN_VERTICALPOSITION_', 'AU_ADMINISTRATIVEUNIT_', 'CP_CADASTRALZONING_', 'TN_ACCESSRESTRICTION_', 'AU_CONDOMINIUM_', 'TN_CONDITIONOFFACILITY_', 'TN_OWNERAUTHORITY_', 'CP_CADASTRALPARCEL_', 'TN_TRAFFICFLOWDIRECTION_', 'TN_MARKERPOST_', 'NET_GRADESEPARATEDCROSSING_', 'CP_BASICPROPERTYUNIT_', 'TN_RESTRICTIONFORVEHICLES_', 'AU_ADMINISTRATIVEBOUNDARY_', 'NET_CROSSREFERENCE_', 'TN_MAINTENANCEAUTHORITY_', 'AD_ADDRESSAREANAME_', 'NET_NETWORK_', 'AD_POSTALDESCRIPTOR_', 'GN_NAMEDPLACE_', 'AD_THOROUGHFARENAME_', 'NET_NETWORKCONNECTION_', 'TN_TRANSPORTNETWORK_', 'CP_CADASTRALBOUNDARY_', 'AD_ADDRESS_', 'AD_ADMINUNITNAME_'._

4. Inserting the _keys_  and _house coordinates_ with one insert action:
Result: Everything works fine (both options: enabled/disabled)

**Comment by tfr42** [comment]
OK, thank you for your feedback. I marked the first action point as done, but for the second we need to  do some investigations why this error occurs. 

@marcus-mohr Can I push your workspace data to a new git repo to share the changes?

**Comment by lgoltz** [comment]
If this feature is used the `idGenMode` **must** be set to `UseExisting`: 
```
<EnableTransactions allowFeatureReferencesToDatastore="true" idGen="UseExisting">true</EnableTransactions>
```
If it is missing (as in the test workspace) or GenerateNew  a new ID is generated during import (step 1), the references cannot be resolved later (in step 3). The exception is thrown cause it is tried to find a feature in the datastore (like a GetFeatureById request), therefor the id must match to the default pattern (`<FEATURETYPE>_<ID>`) .

So there are two requirements, if the feature is used:
 * configure `idGen="UseExisting"`
 * adapt the gml:ids and references  in the data to the pattern `<FEATURETYPE>_<ID>`

Improvement of the documentation (and maybe the logging) is required.

**Comment by tfr42** [comment]
Documentation need to be improved since this is quite important to make this new feature work.

**Comment by marcus-mohr** [comment]
I tested again with idGen="UseExisting" from the beginning (step 1).

My first try failed, because I got the following error:
_Request failed: Cannot perform insert operation: Error inserting feature: Cannot insert feature with id 'AdminUnitName_12051000' and id generation mode 'UseExisting'. Id does not match configured feature id pattern._

Therefore I adjusted the output of the auto-generated featurestore mapping of deegree-cli. For example:
Changed `<FIDMapping prefix="AD_ADMINUNITNAME_">` to `<FIDMapping prefix="AdminUnitName_">`

After this the keys could be stored into DB via WFS-T import. Unfortunately the generated featurestore mapping of deegree-cli uses always integer als data type for gml id... but some id's from the addresses contain characters. So I changed the hale-alignment and the target gml file.  Now the gml:id from address contains only integer values. (The other option I know would be to adjust the DDL and FeatureStore output from deegree-cli but that doesn't seem to be much fun...)

But deegree still produces this error:
_ERROR: [SQLFeatureStoreTransaction] Error inserting feature: FEHLER: Spalte »gid« hat Typ integer, aber der Ausdruck hat Typ character varying
  Hinweis: Sie müssen den Ausdruck umschreiben oder eine Typumwandlung vornehmen.
  Position: 175_

I'm not able to find the "bug" in my data.

Here are the new mapping + the new target gml:
[mapping_targetData.zip](https://github.com/deegree/deegree3/files/1499188/mapping_targetData.zip)

**Comment by lgoltz** [comment]
> (The other option I know would be to adjust the DDL and FeatureStore output from deegree-cli but that doesn't seem to be much fun...)

Which version of the CLI was used? in newer version the type of the id can be passed as argument [1]: `--idtype={int|uuid}, default=int`

Executing `java -jar deegree-cli-utility.jar` without parameter should print details how to use the tool. 

[1] https://github.com/lat-lon/deegree-cli-utility/tree/deegree-3.4

**Comment by lgoltz** [comment]
In the file brb_addresses_integer.gml at least one gml:id with an integer exists: `<ad:Address gml:id="_ac319517-9301-45f7-ad62-75ad309b8a35">`

**Comment by marcus-mohr** [comment]
I already fixed the last gml:id, you were too fast ;) But it's not working and I can't reproduce the error at the moment.

I used the newest version 1.2 of deegree-cli. Neither the integer nor the uuid option seem to fit in a case where the gml id contains strings. Shouldn't there be an argument for strings?

**Comment by marcus-mohr** [comment]
I misunterstood the idtype option "uuid"... of course it's a string! 

I used this attribute to create a new database and now it's possible to import the features which hold a reference to already inserted features! **It's working!**

**Comment by tfr42** [comment]
OK, thanks for the feedback. #860 is updated.
